---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempshell-sa
  namespace: tempshell
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tempshell-role
  namespace: tempshell
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tempshell-rolebinding
  namespace: tempshell
subjects:
  - kind: ServiceAccount
    name: tempshell-sa
    namespace: tempshell
roleRef:
  kind: Role
  name: tempshell-role
  apiGroup: rbac.authorization.k8s.io
