---
# 1. CREATE A SERVICE ACCOUNT
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempshell-sa # Backend uses this account
  namespace: tempshell
---
# 2. DEFINE A ROLE (what actions are allowed)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tempshell-role
  namespace: tempshell
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
# 3. BIND THE ROLE TO THE SERVICE ACCOUNT
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tempshell-rolebinding
  namespace: tempshell
subjects:
  - kind: ServiceAccount
    name: tempshell-sa
    namespace: tempshell
roleRef:
  kind: Role
  name: tempshell-role
  apiGroup: rbac.authorization.k8s.io


# (rbac) Role-Based Access Control.
